adding source.tar

diff --git a/jenkins/raspberrypi/Dockerfile b/jenkins/raspberrypi/Dockerfile
--- a/jenkins/raspberrypi/Dockerfile
+++ b/jenkins/raspberrypi/Dockerfile
@@ -91,7 +91,7 @@ WORKDIR /sdk
 
 RUN git clone https://github.com/$CLIENTLIBRARY_REPO .
 RUN git checkout raspi-pipeline
-RUN git submodule update --init --recursive
+RUN git submodule update --init 
 
 # CMAKE
 RUN mkdir cmake
@@ -117,12 +117,31 @@ RUN make install
 
 ########## PHASE 2: COMPILE BRANCH SPECIFIC INFORMATION ##########
 ARG CLIENTLIBRARY_COMMIT_SHA
-RUN echo $CLIENTLIBRARY_COMMIT_SHA
+ARG CLIENTLIBRARY_COMMIT_NAME
+ARG CLIENTLIBRARY_FORCEFLAG
+
+RUN echo $CLIENTLIBRARY_COMMIT_NAME $CLIENTLIBRARY_COMMIT_SHA 
 WORKDIR /sdk
-RUN git fetch origin 
-RUN git checkout $CLIENTLIBRARY_COMMIT_SHA
-RUN git submodule update --init --recursive
 RUN ls -al
+
+WORKDIR /temp
+COPY ./source.tar.gz /temp/
+RUN if [ -s /temp/source.tar.gz ]; then 
+RUN   mkdir /temp/source
+RUN   [ $? -eq 0 ] || { echo "mkdir /temp/source failed"; exit 1; }
+RUN   tar -zxf /temp/source.tar.gz -C /temp/source 
+RUN   [ $? -eq 0 ] || { echo "tar -zxf failed"; exit 1; }
+RUN   rsync --recursive --checksum --update --delete-during  /temp/source/ .
+RUN   [ $? -eq 0 ] || { echo "rsync failed"; exit 1; }
+RUN else
+RUN   git fetch origin 
+RUN   [ $? -eq 0 ] || { echo "git fetch failed"; exit 1; }
+RUN   git checkout $CLIENTLIBRARY_COMMIT_SHA
+RUN   [ $? -eq 0 ] || { echo "git checkout failed"; exit 1; }
+RUN   git submodule update --init 
+RUN   [ $? -eq 0 ] || { echo "git submodule failed"; exit 1; }
+RUN fi
+
 
 WORKDIR /sdk/cmake
 RUN cmake ..
